### ISSUE TITLE
Default value of `group.initial.rebalance.delay.ms`

### ISSUE THREAD

**Issue by MikeEdgar** [strimzi/test-container#106]
I haven't pinpointed where/how, but version 0.107.0 used to set the value of `group.initial.rebalance.delay.ms` to zero and in 0.108.0 it is now the default of `3000`.

Was it intended to change?

**Comment by see-quick** [comment]
> I haven't pinpointed where/how, but version 0.107.0 used to set the value of `group.initial.rebalance.delay.ms` to zero and in 0.108.0 it is now the default of `3000`.
> 
> Was it intended to change?

Hmm, I think it was because we used the default server.properties file (and then use overrides). Now we are building that file from scratch and copying it into the container. So I think in server.properties the value was set to zero but now as we doing it from scratch it uses default value which is as you pointed out `3000`. I think we can add to the common properties [1] here as it was in `0.107.0`.

[1] - https://github.com/strimzi/test-container/blob/main/src/main/java/io/strimzi/test/container/StrimziKafkaContainer.java#L403-L420

**Comment by scholzj** [comment]
I think we should in general stick with Kafka defaults unless there are some strong reasons and have the option to override the options (I think we have that already) where needed.

**Comment by MikeEdgar** [comment]
No objection from me to stick with the defaults. It was unclear to me how it was being set to `0` in the previous version. I didn't find a reference to that property (outside of a test resource).

**Comment by im-konge** [comment]
Triaged on 14.11.2024: As discussed in the comments (and agreed on the call), we should not change the default value. So I'm closing this as not planned.
